services:
  db:
    image: postgres:latest
    container_name: postgres_db_todo
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
volumes:
  pg_data:
